name: Checkout Upptime repo
description: Check out the repository for Upptime workflows

inputs:
  github-token:
    description: GitHub token for checkout
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        token: ${{ inputs.github-token }}
